
// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI career mentor that provides personalized guidance to students.
 *
 * - provideCareerMentorship - A function that handles the career mentorship process.
 * - ProvideCareerMentorshipInput - The input type for the provideCareerMentorship function.
 * - ProvideCareerMentorshipOutput - The return type for the provideCareerMentorship function.
 */

import {ai} from '@/ai/genkit';
import type { ProvideCareerMentorshipInput, ProvideCareerMentorshipOutput } from '@/ai/schemas';
import { ProvideCareerMentorshipInputSchema, ProvideCareerMentorshipOutputSchema } from '@/ai/schemas';


export async function provideCareerMentorship(
  input: ProvideCareerMentorshipInput
): Promise<ProvideCareerMentorshipOutput> {
  return provideCareerMentorshipFlow(input);
}

const prompt = ai.definePrompt({
  name: 'provideCareerMentorshipPrompt',
  input: {schema: ProvideCareerMentorshipInputSchema},
  output: {schema: ProvideCareerMentorshipOutputSchema},
  prompt: `You are an AI career mentor providing personalized guidance to engineering students.

  A student has asked the following question:
  {{question}}

  Provide a helpful and informative answer to the student's question. Be encouraging and supportive. Make sure to be very detailed and precise in your answer.
  Be specific and tailor your response to the individual student's needs and potential engineering career aspirations.
  Consider a wide range of engineering career paths and offer detailed information for each, depending on the question.
  `, // Ensure detailed and precise answers
});

const provideCareerMentorshipFlow = ai.defineFlow(
  {
    name: 'provideCareerMentorshipFlow',
    inputSchema: ProvideCareerMentorshipInputSchema,
    outputSchema: ProvideCareerMentorshipOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
